# Generated by Django 3.2 on 2025-06-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20250622_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='captain_aadhar',
            field=models.CharField(default='0000000000', max_length=40),
        ),
        migrations.AddField(
            model_name='profiles',
            name='captain_level',
            field=models.CharField(default='Beginner', max_length=15),
        ),
        migrations.AddField(
            model_name='profiles',
            name='captain_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profiles',
            name='captain_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profiles',
            name='created_date',
            field=models.CharField(default='0/0/2025', max_length=15),
        ),
        migrations.AddField(
            model_name='profiles',
            name='rides_count',
            field=models.IntegerField(default=0),
        ),
    ]
